CREATE DATABASE AIRTICKET
CHARACTER SET 'utf8'
COLLATE 'utf8_general_ci';
USE AIRTICKET;
CREATE TABLE USER(
	ID			INT AUTO_INCREMENT PRIMARY KEY,
	USERNAME	TEXT,
	PASSWORD	TEXT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE JOB(
	ID 			INT AUTO_INCREMENT PRIMARY KEY,
	USERID		INT,
	AIRFROM		TEXT,
	AIRTO		TEXT,
	LMONEY		INT,
	FOREIGN KEY(USERID) REFERENCES USER(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE PRICE(
	ID 			INT AUTO_INCREMENT PRIMARY KEY,
	AIRFROM		TEXT,
	AIRTO		TEXT,
	AIRTIME		DATETIME,
	PRICE		INT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;